<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Osdu.Models.Samples.IngestWellLog</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Local project references to the two libraries this sample composes. -->
    <ProjectReference Include="..\..\src\Osdu.Models\Osdu.Models.csproj" />
    <ProjectReference Include="..\..\..\osdu-csharp-client\src\OsduCsharpClient\OsduCsharpClient.csproj" />
  </ItemGroup>

</Project>
